name: testing
on:
  pull_request:
    branches:
      - develop
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TurnStyle
        uses: softprops/turnstyle@v2
      - name: Deploy
        run: sleep 30
