name: testing
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Wait in queue
      - name: TurnStyle
        uses: softprops/turnstyle@v2

      # Set up Node.js version 20.17
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17'

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Run tests
      - name: Run tests
        run: |
          npx playwright install --with-deps
          npm run e2e
      # Save report on failure
      - name: Save report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./e2e/temp/test-results/

      - name: Build
        run: npm run build
