name: testing
on:
  pull_request:
    branches:
      - develop
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ahmadnassri/action-workflow-queue@v1
      - name: Deploy
        run: sleep 40
