name: testing
on:
  pull_request:
    branches:
      - develop
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Turnstyle
        uses: softprops/turnstyle@v2
        with:
          same-branch-only: false
      - name: Deploy
        run: sleep 40
